import oracledb
import sys

# 1. 오라클 데이터베이스 접속 정보 설정
DB_CONFIG = {
    "user": "system",
    "password": "1234",
    "dsn": "localhost:1521/xe"
}

def get_connection():
    """데이터베이스 연결 객체를 생성하여 반환합니다."""
    try:
        conn = oracledb.connect(
            user=DB_CONFIG["user"],
            password=DB_CONFIG["password"],
            dsn=DB_CONFIG["dsn"]
        )
        return conn
    except oracledb.Error as e:
        print(f"  DB 접속 실패: {e}")
        sys.exit(1)

def setup_database(cursor):
    """실습을 위한 테이블을 생성합니다."""
    try:
        cursor.execute("DROP TABLE CAFE_SALES")
    except oracledb.Error:
        pass

    # 요구사항 정의서에 명시된 테이블 설계 적용
    cursor.execute("""
        CREATE TABLE CAFE_SALES (
            SALE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            MENU_NAME VARCHAR2(50) NOT NULL,
            PRICE NUMBER NOT NULL,
            SALE_DATE DATE DEFAULT SYSDATE
        )
    """)

def insert_sales_data(cursor, order_string, menu_db):
    """입력받은 문자열 데이터를 파싱하여 DB에 저장합니다."""
    # split()을 사용하여 입력 데이터를 분리
    orders = order_string.split(',')
    
    insert_sql = "INSERT INTO CAFE_SALES (MENU_NAME, PRICE) VALUES (:1, :2)"
    inserted_count = 0
    
    for item in orders:
        item = item.strip() # 공백 제거
        if item in menu_db:
            cursor.execute(insert_sql, (item, menu_db[item]))
            inserted_count += 1
        else:
            print(f"⚠️ 경고: 메뉴판에 없는 '{item}'은(는) 제외되었습니다.")
            
    return inserted_count

def get_sales_report(cursor):
    """SQL 집계 함수를 사용하여 매출 보고서 데이터를 조회합니다.[cite: 1]"""
    query = """
        SELECT 
            COUNT(*) AS total_count, 
            NVL(SUM(PRICE), 0) AS total_revenue,
            LISTAGG(MENU_NAME, ', ') WITHIN GROUP (ORDER BY SALE_ID) AS menu_list
        FROM CAFE_SALES
    """
    cursor.execute(query)
    return cursor.fetchone()

# ---------------------------------------------------------
# 2. 메인 실행 진입점[cite: 1]
# ---------------------------------------------------------
if __name__ == "__main__":
    # 메뉴판 데이터 (딕셔너리 구조)[cite: 1]
    menu_prices = {
        "아메리카노": 3000,
        "카페라떼": 4000,
        "카푸치노": 3500,
        "에스프레소": 2500
    }

    conn = get_connection()
    cursor = conn.cursor()

    try:
        # DB 초기 설정 (테이블 생성)
        setup_database(cursor)
        
        print("--- ☕️ 카페 매출 관리 시스템 (Oracle) ---")
        print(f"판매 가능 메뉴: {', '.join(menu_prices.keys())}")
        
        # 3. 사용자로부터 직접 입력 받기 (input 문법 활용)[cite: 1]
        user_input = input("\n오늘 판매된 메뉴들을 쉼표(,)로 구분하여 입력하세요\n> ")
        
        # 데이터 적재 (DML)
        count_inserted = insert_sales_data(cursor, user_input, menu_prices)
        conn.commit() # 트랜잭션 확정[cite: 1]
        
        if count_inserted > 0:
            print(f"\n✅ {count_inserted}건의 데이터가 DB에 정상 저장되었습니다.")

            # 보고서 데이터 조회 (DQL)
            report = get_sales_report(cursor)
            count, revenue, items = report

            # 최종 보고서 출력[cite: 1]
            print("\n" + "="*45)
            print("      --- 일일 매출 분석 보고서 (DB) ---")
            print(f"   총 판매 건수 : {count}건")
            print(f"   총 매출액   : {revenue:,}원")
            print("-" * 45)
            print(f"   판매된 리스트: {items if items else '없음'}")
            print("="*45)
        else:
            print("\nℹ️ 입력된 유효한 판매 데이터가 없습니다.")

    except oracledb.Error as e:
        print(f"⚠️ SQL 실행 오류 발생: {e}")
        conn.rollback() # 오류 시 복구[cite: 1]
    finally:
        # 자원 반납[cite: 1]
        cursor.close()
        conn.close()