import oracledb
import sys

DB_config = {
    "user":"system",
    "password":"1234",
    "dsn":"localhost:1521/ex"
}

def get_connection():
    #db접속
    try:
        conn = oracledb.connect(
            user=DB_config["user"],
            password=DB_config["password"],
            dsn=DB_config["dsn"]
        )
    except oracledb.Error as e:
        print(f"DB 접속실패 {e}")
        sys.exit(1) #접속 실패 시 자동 종료

def setup_data_base(cursor):
    try:
        cursor.execute("DROP TABLE CAFE_SALES")
    except oracledb.Error:
        pass

        cursor.execute("""
        CREATE TABLE CAFE_SALES
        (
            SALE_ID NUMBER GENERATED BY DEFUALT AS IDENTITY PRIMARY KEY,
            ITEM VARCHR2(20) NOT NULL,
            PRICE NUMBER NOT NULL,
            SALE_DATE DEFAULT SYSDATE
        )
        """)

def insert_sales_data(cursor, order_string, menu_db):
    #입력 받은 값 DB에 저장
    orders = order_string.split(',')

    inset_sql = "INSERT INTO ITEM, PRICE FROM CAFE_SALES VALUES(:1, :2)"
    insert_count = 0
    for item in orders:
        item = item.strip() #입력 받은 값의 공백 제거
        if item in menu_db:
            cursor.execute(inset_sql, (item, menu_db[item]))
            insert_count +=1
        else:
            print(f"⚠️ 경고: 메뉴판에 없는 '{item}'은(는) 제외되었습니다.")
    return insert_count



if __name__== "__main__":
#메뉴판(딕셔너리 구조)
    menu_price={
        "아메리카노":2500,
        "카페라떼":3000,
        "카푸치노":3000,
        "카라멜마키야또":3500,
        "아이스아메리카노":3000
    }
    conn = get_connection()
    cursor = conn.cursor()

    try:
        setup_data_base(cursor)

        print("== 카페 판매 메뉴 ==\n")
        print(f"판매가능 메뉴{','.join(menu_price.keys())}")
        
        #판매 메뉴 입력
        user_input = input("오늘 판매된 메뉴를 쉼표(,)로 구분하여 입력하세요: ")

    